before_script:
  mkdir -p "phpwarrior/test-beginner/"
  curl https://gist.githubusercontent.com/yandod/31166f8ee21f22105e92/raw/86e5a37c4e832c8af2b6cc93c51963331898b9fe/player.php phpwarrior/test-begginer/player.php

script:
  ./bin/phpwarrior -d phpwarrior/test-beginner/ -t 0 -s
